spring.application.name=disasterrecovery
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/disaster_recovery_db
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.task.scheduling.pool.size=10
backup.storage.location=E:/downloadsE/profile/Stackly_office/JAVA & MYSQL notes/Task/Disaster Recovery & Backup System/backups
backup.retention.days=30
aws.s3.bucket=dr-backup-bucket

management.endpoints.web.exposure.include=*
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

logging.level.com.example.disasterrecovery=DEBUG
