package com.example.cdc_synchronization_engine.exception;

public enum ErrorCode {

    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    INVALID_REQUEST,
    INVALID_OPERATION,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    JWT_EXPIRED,
    JWT_INVALID,
    DATABASE_ERROR,
    KAFKA_PUBLISH_FAILED,
    KAFKA_CONSUME_FAILED,
    CDC_PROCESSING_FAILED,
    ELASTICSEARCH_SYNC_FAILED,
    IDEMPOTENCY_ERROR,
    RETRY_LIMIT_EXCEEDED,
    DEAD_LETTER_QUEUE_ERROR,
    INTERNAL_SERVER_ERROR
}