package com.example.multiregion_resilience.exception;

public enum ErrorCode {

    REGION_NOT_FOUND,
    REGION_ALREADY_EXISTS,
    REGION_UNAVAILABLE,
    INVALID_REGION_STATUS,
    INVALID_FAILOVER_REQUEST,
    FAILOVER_FAILED,
    FAILBACK_FAILED,
    NO_HEALTHY_REGION_AVAILABLE,
    CACHE_SYNC_FAILED,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_CONFLICT,
    IDEMPOTENCY_PROCESSING,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    INVALID_OPERATION,
    OPTIMISTIC_LOCK_CONFLICT,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR, 
    FAILOVER_EVENT_NOT_FOUND
}
